### ISSUE TITLE
Upgrading to Spring Boot 2.4.3

### ISSUE THREAD

**Issue by ikyrannas** [sastix/cms#5]
# Purpose
As a means of getting familiar with the code and in order for the project to get advantage of the latest advances in the Spring framework we could advance to Spring Boot 2.4.3 ( the latest stable version as of now).

# Steps
- Cover existing functionality with tests where needed in order to avoid regression.
- Migrate Spring Boot parent to the latest version and check for dependency conflicts.
- Refactor the code in the modules to comply with the changes.
- Submit when tests are satisfied.

# (Optionally) Upgrade to JDK 11 (LTS)
The JDK 8 support is announced to be discontinued as per the Oracle Java SE Support Roadmap. Migration to JDK 11 should be an easy task as Java written with JDK 8 can be compiled and run in the JVM for JDK 11.

If this is ok I will be available to work on that and submit a pull request.

**Comment by iskitsas** [comment]
Hi Ilias,

Yes this would be great

**Comment by ikyrannas** [comment]
Hi,

I think this is closed now. Thanks for accepting the PR.
